name: Ask a customization question
description: I have a question about the build or customization of Identity Manager HTML5 web applications
labels:
  - bug
  
body:
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      description: This used to work and it doesn't anymore
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the impact of this issue?
      options:
        - ⚪ Cosmetic – visual or non-functional issue
        - 🟡 Minor – small but noticeable issue
        - 🟠 Major – significantly affects usability
        - 🔴 Critical – blocks key functionality
    validations:
      required: true
  
  - type: dropdown
    id: affected-branch
    attributes:
      label: Please provide the branch(es) you discovered this issue in
      options:
        - v100
        - v93
        - v92
        - v91
        - v90
      multiple: true
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment Details
      description: Include browser, OS, and One Identity Manager version. Product version is available on the admin portal homepage.
      placeholder: e.g. Chrome 129 on Windows 11, 9.3 v93-329250
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Please provide a minimal set of steps to reproduce the issue
      placeholder: |
        1. First step
        2. Second step
        3. and so on...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the issue you encountered
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual-behavior
    attributes:
      label: Describe what you expected to happen versus what actually happened
      placeholder: |
        I would expect that...
        Instead, what I see...
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or console output
      description: Paste logs or browser console errors here (if applicable)
      render: shell

  - type: textarea
    id: screenshot
    attributes:
      label: Add a screenshot(s) if that helps illustrate the problem

  - type: textarea
    id: proposed-solution
    attributes:
      label: Suggested Fix
      description: If you have an idea for how this could be resolved, describe it here.
      placeholder: Replace line 123 in example.component.ts with this code....

  - type: textarea
    id: other
    attributes:
      label: Anything else?
      placeholder: e.g additional comments, architectural concerns, etc.
      
  - type: checkboxes
    id: verification
    attributes:
      label: Before submitting...
      options:
        - label: My issue is a customization issue that is not covered by product support
          required: true
        - label: I have included all necessary details to reproduce this issue
          required: true
