name: Documentation

on:
  push:
    branches: [master, v92, change/v92/testForActions]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./imxweb
        run: npm install

      - name: Generate documentation for qbm
        run: npm run doc:qbm
        working-directory: ./imxweb

      - name: Generate documentation for qer
        run: npm run doc:qer
        working-directory: ./imxweb

      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          path: 'doc-files'
          ref: 'main'
          repository: 'OneIdentity/IdentityManager.ImxDoc'
          token: ${{ secrets.GHPAGES_ACCESS_TOKEN}}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to folder
        shell: bash
        run: |
          rm -r "doc-files/documentation/v92"
          mkdir -p "doc-files/documentation/v92"
          cp -rvT "imxweb/documentation/v92" "doc-files/documentation/v92"

      - name: Commit files to doc repository
        id: newFiles
        shell: bash
        working-directory: doc-files
        run: |
          git config --global user.name "Automatic compoDoc documentation"
          git config --global user.email "martina.graeber@oneidentity.com"
          git add .
          git commit -m "Automatic compoDoc documentation"
          git push