name: Documentation

on:
  push:
    branches: [master, v92, change/v92/testForActions]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./imxweb
        run: npm install

      - name: Generate documentation for qbm
        run: npm run doc:qbm
        working-directory: ./imxweb

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs