name: Documentation

on:
  push:
    branches: [master, v92, change/v92/testForActions]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    env: 
      TEST_TOKEN: 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
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./imxweb
        run: npm install

      - name: Generate documentation for qbm
        run: npm run doc:qbm
        working-directory: ./imxweb

      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          path: 'doc-files'
          ref: 'main'
          repository: 'OneIdentity/IdentityManager.ImxDoc'
          token: ${{ env.TEST_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to folder
        shell: bash
        run: |
          mkdir -p "doc-files/doc"
          cp -rvT "imxweb/doc/v92" "doc-files/doc"

      - name: Commit files to doc repository
        id: newFiles
        shell: bash
        working-directory: doc-files
        run: |
          git config --global user.name "Automatic compoDoc documentation"
          git config --global user.email "martina.graeber@oneidentity.com"
          git add .
          git commit -m "Automatic compoDoc documentation"
          git push
          
    # env:
    #   CI_COMMIT_MESSAGE: Automatic compoDoc documentation
    #   CI_COMMIT_AUTHOR: Compodoc Integration Process
    # steps:

    # #ToDO: I need to change the repo here

    # - name: GIT Commit Documentation
    # # Only run on main branch push (e.g. pull request merge).
    #   if: github.event_name == 'push'
    #   run: |
    #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
    #     git config --global user.email "martina.graeber@oneidentity.com"
    #     git add imxweb/doc
    #     git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
    #     git push
