name: Documentation

on:
  push:
    branches: [master, v92, change/v92/testForActions]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./imxweb
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        project: [qbm, qer]
    steps:
      - name: Generate documentation for ${{matrix.project}}
        run: npm run doc:${{matrix.project}}
        working-directory: imxweb

  copy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          path: 'documentation'
          ref: 'main'
          repository: 'OneIdentity/IdentityManager.ImxDoc'
          token: ${{ secrets.GHPAGES_ACCESS_TOKEN}}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy files to folder
        shell: bash
        run: |
          rm -r "documentation/v92"
          mkdir -p "documentation/v92"
          cp -rvT "imxweb/documentation/v92" "documentation/v92"   

      - name: Commit files to doc repository
        id: newFiles
        shell: bash
        working-directory: documemtation # todo: Struktur festlegen (auch oben)
        run: |
          git config --global user.name "Automatic compoDoc documentation"
          git config --global user.email "martina.graeber@oneidentity.com"
          git add .
          git commit -m "Automatic compoDoc documentation"
          git push