name: Documentation

on:
  push:
    branches: [master, v92, change/v92/testForActions]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./imxweb
        run: npm install

      - name: Generate documentation for qbm
        run: npm run doc:qbm
        working-directory: ./imxweb

      - name: Deploy the documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ./documentation/ # or path/to/artifact