name: Build Angular applications

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, v82, v90, v92]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # Verhindert Probleme mit GitHub Actions Token

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        working-directory: ./imxweb
        run: npm install

      # Build & ZIP der Anwendungen
      - name: Build and ZIP all applications
        working-directory: ./imxweb
        run: |
          mkdir -p .autodeploy/bin/imxweb/custom
          APPS=("qbm" "qer" "tsb" "att" "rms" "aad" "aob" "uci" "cpl" "dpr" "rmb" "rps" "o3t" "olg" "hds" "pol" "qer-app-portal" "qbm-app-landingpage" "qer-app-operationssupport" "qer-app-pwdportal" "custom-app")

          for APP in "${APPS[@]}"; do
            echo "-------------------------------------"
            echo "Building $APP..."
            npm run build "$APP"

            if [ -d "dist/$APP" ]; then
              echo "✅ Found dist/$APP, creating ZIP..."
              zip -r "HTML_${APP}.zip" "dist/$APP"
              mv "HTML_${APP}.zip" .autodeploy/bin/imxweb/custom/
            else
              echo "❌ WARNING: dist/$APP not found, skipping ZIP creation!"
            fi
          done

      # Debugging: Überprüfen, ob ZIP-Dateien erstellt wurden
      - name: List generated ZIP files
        run: ls -lah ./imxweb/.autodeploy/bin/imxweb/custom/

      # ✅ ZIP-Dateien ins Repository committen & pushen
      - name: Commit and Push ZIPs to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .autodeploy/bin/imxweb/custom/*.zip

          # Falls es keine Änderungen gibt, beenden
          git diff --staged --quiet || git commit -m "Automated: Add new build ZIPs"

          # Änderungen pushen (nutzt das GitHub Actions Token)
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
