name: Build Angular workspace

on:
  push:
    branches: [ v100 ]
  pull_request:
    branches: [ v100, v93 ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

      # Only run the matching matrix entry for the current branch
    if: github.ref_name == matrix.branch
    strategy:
      matrix:
        include:
          - branch: v100
            node-version: 22.x
            os: windows-latest
          - branch: v93
            node-version: 20.x
            os: windows-latest
  
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      working-directory: ./imxweb
      run: npm install --skip-dialog

    - name: Build All
      working-directory: ./imxweb
      run: npm run nx:build-all
      timeout-minutes: 25

    - name: Test All
      working-directory: ./imxweb
      run: npm run nx:test-ci
      timeout-minutes: 25
