name: Build Angular applications

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, v82, v90, v92]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v4 # Aktualisierte Version

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Aktualisierte Version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        working-directory: ./imxweb
        run: npm install

      # Liste der Applikationen
      - name: Build and ZIP all applications
        working-directory: ./imxweb
        run: |
          mkdir -p .autodeploy/bin/imxweb/custom
          APPS=("qbm" "qer" "tsb" "att" "rms" "aad" "aob" "uci" "cpl" "dpr" "rmb" "rps" "o3t" "olg" "hds" "pol" "qer-app-portal" "qbm-app-landingpage" "qer-app-operationssupport" "qer-app-pwdportal" "custom-app")

          for APP in "${APPS[@]}"; do
            echo "Building $APP..."
            npm run build "$APP"
            
            if [ -d "dist/$APP" ]; then
              echo "Creating ZIP for $APP..."
              zip -r "HTML_${APP}.zip" "dist/$APP"
              mv "HTML_${APP}.zip" .autodeploy/bin/imxweb/custom/
            else
              echo "Warning: dist/$APP not found, skipping ZIP..."
            fi
          done

      # Hochladen der ZIP-Dateien als Artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Angular Build ZIPs
          path: .autodeploy/bin/imxweb/custom/*.zip
          retention-days: 7
